### ISSUE TITLE
WebSerial embed

### ISSUE THREAD

**Issue by ra1n08** [ayushsharma82/WebSerial#45]
I want to embed WebSerial in my ui webpage without having to display it in WebSerial's webpage, how do I do that?

**Comment by abuisine** [comment]
Hi there, I got the same kind of potential usage : I use WebSerial Pro and would like to integrate it into my settings webpage, through an iframe I get a barely usable page.
Would be great to at least be able to disable the main logo in order to reduce the layout footprint of WebSerial.
Thanks for the cool library btw !

**Comment by ayushsharma82** [comment]
Hi @ra1n08 & @abuisine ,

There is currently no way to embed it into another page as it's a `javascript` bundle.

I would like to suggest using a full page iframe.
